### ISSUE TITLE
Inline comment ending with semicolon breaks ability to add semicolons

### ISSUE THREAD

**Issue by KamilTheDev** [myaaghubi/Auto-Semicolon-VSCode#7]
If I comment out some code, lets say:
```csharp
int number = //a();
```
and I want to write `b();` instead, when trying to add the semicolon, it will jump to the end of the comment and not add the semicolon.
```csharp
int number = b() //a();
```
Video:

https://github.com/user-attachments/assets/8ee0bbe6-a6b6-4c40-9917-50b66c579f2b

**Comment by KamilTheDev** [comment]
The issue is if the inline comment ends with a `;`, which occurs frequently when commenting out inline code.

For example, you cannot put a semicolon after `a` in the following code:
```cs
int number = a //;
```

**Comment by myaaghubi** [comment]
Actually, you can put `;` manually for this king situation, check for readme
- `alt + ;` then `;` > To put `;` right in place (not auto)

For the issue, I'll release a bug fix as soon as I can :v:

**Comment by myaaghubi** [comment]
Checkout f47c373d19f3de4d3270c16db744d2131d5adb01
